// Canonical domain for SEO (used for canonical + OG URL + sitemap/robots)
export const baseUrl = 'https://axiwatt.com';

export const seoConfig = {
  home: {
    title: 'Axiwatt – Energy Autonomy Solutions',
    description: 'Transform your private estate with sustainable power autonomy. Axiwatt integrates architecture and renewable energy for intelligent, off-grid living.',
    keywords: 'luxury solar architecture, solar energy systems, renewable energy, solar pergolas, solar glass facades, sustainable architecture, high-end solar solutions, energy autonomy, private estates',
    ogTitle: 'Axiwatt – Energy Autonomy Solutions',
    ogDescription: 'Transform your private estate with sustainable power autonomy. Axiwatt integrates architecture and renewable energy for intelligent, off-grid living.',
    ogImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    ogImageWidth: '1200',
    ogImageHeight: '630',
    ogUrl: baseUrl,
    ogType: 'website',
    twitterCard: 'summary_large_image',
    twitterTitle: 'Axiwatt – Energy Autonomy Solutions',
    twitterDescription: 'Transform your private estate with sustainable power autonomy. Axiwatt integrates architecture and renewable energy for intelligent, off-grid living.',
    twitterImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    canonicalUrl: baseUrl
  },
  about: {
    title: 'Luxury Energy Autonomy for Estates | Axiwatt',
    description: 'Discover bespoke energy autonomy systems for premium properties. Axiwatt blends smart design with renewable power for sustainable living.',
    keywords: 'solar architecture firm, renewable energy company, luxury estate development, sustainable architecture, energy governance, private collective',
    ogTitle: 'Luxury Energy Autonomy for Estates | Axiwatt',
    ogDescription: 'Discover bespoke energy autonomy systems for premium properties. Axiwatt blends smart design with renewable power for sustainable living.',
    ogImage: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&q=80&w=1200',
    ogImageWidth: '1200',
    ogImageHeight: '630',
    ogUrl: `${baseUrl}/about`,
    ogType: 'website',
    twitterCard: 'summary_large_image',
    twitterTitle: 'Luxury Energy Autonomy for Estates | Axiwatt',
    twitterDescription: 'Discover bespoke energy autonomy systems for premium properties. Axiwatt blends smart design with renewable power for sustainable living.',
    twitterImage: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&q=80&w=1200',
    canonicalUrl: `${baseUrl}/about`
  },
  products: {
    title: 'Axiwatt – Solar & Renewable Energy Architecture',
    description: 'Leading energy autonomy provider offering solar architecture and intelligent energy systems tailored to distinguished residences.',
    keywords: 'solar pergolas, solar glass facades, solar railings, walkable solar tiles, building-integrated photovoltaics, BIPV, bioclimatic pergolas',
    ogTitle: 'Axiwatt – Solar & Renewable Energy Architecture',
    ogDescription: 'Leading energy autonomy provider offering solar architecture and intelligent energy systems tailored to distinguished residences.',
    ogImage: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&q=80&w=1200',
    ogImageWidth: '1200',
    ogImageHeight: '630',
    ogUrl: `${baseUrl}/products`,
    ogType: 'website',
    twitterCard: 'summary_large_image',
    twitterTitle: 'Axiwatt – Solar & Renewable Energy Architecture',
    twitterDescription: 'Leading energy autonomy provider offering solar architecture and intelligent energy systems.',
    twitterImage: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&q=80&w=1200',
    canonicalUrl: `${baseUrl}/products`
  },
  technology: {
    title: 'Smart Energy-Independent Architecture by Axiwatt',
    description: 'Achieve complete energy independence with Axiwatt\'s intelligent renewable energy solutions for private estates.',
    keywords: 'solar technology, energy storage, EV charging, solar modules, battery systems, renewable energy management, Axiwatt OS, intelligent energy systems',
    ogTitle: 'Smart Energy-Independent Architecture by Axiwatt',
    ogDescription: 'Achieve complete energy independence with Axiwatt\'s intelligent renewable energy solutions for private estates.',
    ogImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    ogImageWidth: '1200',
    ogImageHeight: '630',
    ogUrl: `${baseUrl}/technology`,
    ogType: 'website',
    twitterCard: 'summary_large_image',
    twitterTitle: 'Smart Energy-Independent Architecture by Axiwatt',
    twitterDescription: 'Achieve complete energy independence with intelligent renewable energy solutions for private estates.',
    twitterImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    canonicalUrl: `${baseUrl}/technology`
  },
  process: {
    title: 'Renewable Energy Architecture Services | Axiwatt',
    description: 'Build energy efficient and autonomous living spaces with Axiwatt\'s comprehensive renewable system designs.',
    keywords: 'architects, designers, solar integration, BIM tools, architectural collaboration, sustainable design, integrated solar architecture',
    ogTitle: 'Renewable Energy Architecture Services | Axiwatt',
    ogDescription: 'Build energy efficient and autonomous living spaces with Axiwatt\'s comprehensive renewable system designs.',
    ogImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    ogImageWidth: '1200',
    ogImageHeight: '630',
    ogUrl: `${baseUrl}/process`,
    ogType: 'website',
    twitterCard: 'summary_large_image',
    twitterTitle: 'Renewable Energy Architecture Services | Axiwatt',
    twitterDescription: 'Build energy efficient and autonomous living spaces with comprehensive renewable system designs.',
    twitterImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    canonicalUrl: `${baseUrl}/process`
  },
  partners: {
    title: 'Axiwatt – Intelligent Solar Architecture Experts',
    description: 'Bespoke solar architecture and sustainability solutions designed for energy-independent estates.',
    keywords: 'concierge services, energy management, lifecycle management, private services, regulatory stewardship, energy consulting, maintenance',
    ogTitle: 'Axiwatt – Intelligent Solar Architecture Experts',
    ogDescription: 'Bespoke solar architecture and sustainability solutions designed for energy-independent estates.',
    ogImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    ogImageWidth: '1200',
    ogImageHeight: '630',
    ogUrl: `${baseUrl}/partners`,
    ogType: 'website',
    twitterCard: 'summary_large_image',
    twitterTitle: 'Axiwatt – Intelligent Solar Architecture Experts',
    twitterDescription: 'Bespoke solar architecture and sustainability solutions designed for energy-independent estates.',
    twitterImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    canonicalUrl: `${baseUrl}/partners`
  },
  privacy: {
    title: 'Privacy Policy | AxiWatt',
    description: 'Learn how AxiWatt protects your data and respects your privacy. Our policy explains collecting, storing, and using personal information.',
    keywords: 'privacy policy, data protection, confidentiality, security, personal data, GDPR, data rights',
    ogTitle: 'Privacy Policy | AxiWatt',
    ogDescription: 'Learn how AxiWatt protects your data and respects your privacy.',
    ogImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    ogImageWidth: '1200',
    ogImageHeight: '630',
    ogUrl: `${baseUrl}/privacy`,
    ogType: 'website',
    twitterCard: 'summary_large_image',
    twitterTitle: 'Privacy Policy | AxiWatt',
    twitterDescription: 'Learn how AxiWatt protects your data and respects your privacy.',
    twitterImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    canonicalUrl: `${baseUrl}/privacy`
  },
  terms: {
    title: 'Terms & Conditions | AxiWatt',
    description: 'Read the terms and conditions governing the use of AxiWatt\'s website and services — transparency and user trust guaranteed.',
    keywords: 'terms of service, terms and conditions, legal terms, user agreement, service terms',
    ogTitle: 'Terms & Conditions | AxiWatt',
    ogDescription: 'Read the terms and conditions governing the use of AxiWatt\'s website and services.',
    ogImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    ogImageWidth: '1200',
    ogImageHeight: '630',
    ogUrl: `${baseUrl}/terms`,
    ogType: 'website',
    twitterCard: 'summary_large_image',
    twitterTitle: 'Terms & Conditions | AxiWatt',
    twitterDescription: 'Read the terms and conditions governing the use of AxiWatt\'s website and services.',
    twitterImage: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1200',
    canonicalUrl: `${baseUrl}/terms`
  }
};
